# Generated by Django 4.0.3 on 2022-03-31 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlayerApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='MusicId',
        ),
        migrations.AddField(
            model_name='music',
            name='CategoryId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musicPlayerApi.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='MusicFile',
            field=models.FileField(upload_to='uploads/MusicFile'),
        ),
        migrations.AlterField(
            model_name='music',
            name='PhotoCover',
            field=models.ImageField(upload_to='uploads/PhotoCover'),
        ),
    ]
