# Generated by Django 4.0.3 on 2022-06-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlayerApi', '0003_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='AlbumName',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
