# Generated by Django 4.0.3 on 2022-09-03 15:20

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlayerApi', '0004_album_albumname'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='color',
            field=colorfield.fields.ColorField(default='#76b96a', image_field=None, max_length=18, samples=None),
        ),
    ]
