# Generated by Django 4.0.3 on 2022-09-18 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicPlayerApi', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayListName', models.TextField()),
                ('CreatedAt', models.DateField(default=django.utils.timezone.now)),
                ('SongID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicPlayerApi.music')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PlayList',
            },
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='MusicId',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='UserId',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comment'},
        ),
        migrations.RenameField(
            model_name='liked',
            old_name='MusicId',
            new_name='SongID',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
