# Generated by Django 4.1.5 on 2023-01-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlayerApi', '0007_playlist_remove_favourite_musicid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='color',
        ),
        migrations.AddField(
            model_name='music',
            name='Artist',
            field=models.TextField(default='01/01/1970'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='PhotoCover',
            field=models.ImageField(default='01/01/1970', upload_to='uploads/PhotoCover'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
