# Generated by Django 4.1.5 on 2023-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlayerApi', '0008_remove_music_color_music_artist_playlist_photocover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='Description',
            field=models.TextField(default='sdfds'),
            preserve_default=False,
        ),
    ]
