# Generated by Django 4.1.5 on 2023-02-03 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicPlayerApi', '0009_playlist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='SongID',
        ),
        migrations.CreateModel(
            name='SongsAddedToPlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateField(default=django.utils.timezone.now)),
                ('PlayListId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicPlayerApi.playlist')),
                ('SongID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicPlayerApi.music')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AddToPlayList',
            },
        ),
    ]
