# Generated by Django 4.1.5 on 2023-02-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlayerApi', '0010_remove_playlist_songid_songsaddedtoplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='PlayListName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
