# Generated by Django 5.2.3 on 2025-07-01 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlayerApi', '0010_remove_playlist_songid_songsaddedtoplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='CreatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
