# Generated by Django 4.1.5 on 2023-02-17 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlayerApi', '0012_alter_playlist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CreatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='liked',
            name='CreatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='music',
            name='CreatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='CreatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='PhotoCover',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/PhotoCover'),
        ),
        migrations.AlterField(
            model_name='songsaddedtoplaylist',
            name='CreatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
