# Generated by Django 4.1.6 on 2023-08-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlayerApi', '0013_alter_category_createdat_alter_liked_createdat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songsaddedtoplaylist',
            options={'verbose_name_plural': 'songs in playlist'},
        ),
        migrations.AlterField(
            model_name='playlist',
            name='PhotoCover',
            field=models.ImageField(blank=True, default='https://images.pexels.com/photos/3944091/pexels-photo-3944091.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', null=True, upload_to='uploads/PhotoCover'),
        ),
    ]
